version: "3.1"

services:
  session-db:
    image: postgres
    restart: always
    ports:
      - 5435:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: session-control

    volumes:
      - pgdata:/var/lib/postgresql/data

  session-control-redis:
    image: redis
    container_name: redis-session-control
    ports:
      - 6380:6379

volumes:
  pgdata:
